// <auto-generated>
// THIS (.cs) FILE IS GENERATED BY `Serializers/TupleSerializers.tt`. DO NOT CHANGE IT.
// </auto-generated>
#nullable enable
namespace FakeCsvSerializer.Tests;

public partial class TupleSerializersTest
{
    [Fact]
    public void Serializer_tuple1()
    {
        var t = Tuple.Create(1);
        RunTest(t, @"""1""", CsvSerializerOptions.Default);
    }
    [Fact]
    public void Serializer_tuple2()
    {
        var t = Tuple.Create(1, 2);
        RunTest(t, @"""1"",""2""", CsvSerializerOptions.Default);
    }
    [Fact]
    public void Serializer_tuple3()
    {
        var t = Tuple.Create(1, 2, 3);
        RunTest(t, @"""1"",""2"",""3""", CsvSerializerOptions.Default);
    }
    [Fact]
    public void Serializer_tuple4()
    {
        var t = Tuple.Create(1, 2, 3, 4);
        RunTest(t, @"""1"",""2"",""3"",""4""", CsvSerializerOptions.Default);
    }
    [Fact]
    public void Serializer_tuple5()
    {
        var t = Tuple.Create(1, 2, 3, 4, 5);
        RunTest(t, @"""1"",""2"",""3"",""4"",""5""", CsvSerializerOptions.Default);
    }
    [Fact]
    public void Serializer_tuple6()
    {
        var t = Tuple.Create(1, 2, 3, 4, 5, 6);
        RunTest(t, @"""1"",""2"",""3"",""4"",""5"",""6""", CsvSerializerOptions.Default);
    }
    [Fact]
    public void Serializer_tuple7()
    {
        var t = Tuple.Create(1, 2, 3, 4, 5, 6, 7);
        RunTest(t, @"""1"",""2"",""3"",""4"",""5"",""6"",""7""", CsvSerializerOptions.Default);
    }
    [Fact]
    public void Serializer_tuple8()
    {
        var t = Tuple.Create(1, 2, 3, 4, 5, 6, 7, 8);
        RunTest(t, @"""1"",""2"",""3"",""4"",""5"",""6"",""7"",""8""", CsvSerializerOptions.Default);
    }
}